:fields: localTimestamp,swell.components.combined.*,wind.speed,charts.swell
:messages:
  :start: "ğŸ§‘â€ğŸ’»Author @eddygarcas Github https://github.com/eddygarcas\nThanks for using BcnSurfBot\nğŸŒŠ All data is provided by magicseaweed.com"
  :error: "ğŸ¤–Oops! Something went wrong, please press /start button again."
  :help: "â„¹ï¸ Use inline buttons below here or type the inline command @bcnsurfbot in any chat, the bot will prompt all surf spots available."
  :inline: "ğŸ”˜ Select one surf spot available"
  :link_msw: "â„¹ï¸ More at https://magicseaweed.com/"
:spots:
  barcelona:
    :id: 3535
    :name: Barceloneta
    :latitude: 41.374017
    :longitude: 2.189929
    :units: eu
  sitges:
    :id: 3536
    :name: Sitges
    :latitude: 41.235629
    :longitude: 1.827288
    :units: eu
  masnou:
    :id: 3530
    :name: Masnou
    :latitude: 41.475521
    :longitude: 2.307683
    :units: eu
  zarautz:
    :id: 1061
    :name: Zarautz
    :latitude: 43.288991
    :longitude: -2.164308
    :units: eu
  mundaka:
    :id: 169
    :name: Mundaka
    :latitude: 43.407004
    :longitude: -2.696284
    :units: eu
  sopelana:
    :id: 1124
    :name: Sopelana
    :latitude: 43.384445
    :longitude: -3.003459
    :units: eu
:actions:
  :spots:
    barcelona:
    sitges:
    masnou:
    zarautz:
    mundaka:
    sopelana:
  :inputs:
    setheight:
